version: "3.8"

services:
  elasticsearch:
    image: elasticsearch:8.16.6
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    restart: always

  kibana:
    image: kibana:8.16.6
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    restart: always

  rabbitmq:
    image: rabbitmq:3-management # Management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672" # AMQP protocol
      - "15672:15672" # Web management panel
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: OnionTest
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  elasticsearch-data:
  rabbitmq-data:
  postgres-data:
